version: '3.9'
services:
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=gobank
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
  
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/gobank?sslmode=disable
    depends_on:
      - postgres
